import { SessionProvider } from 'next-auth/react'
import { Providers } from './providers'
import Navbar from './Navbar/page';
import '@fontsource/archivo-black';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const style = {
    margin: 0,
    padding: 0,
    height: "100%",
    width: "100%",
    fontFamily:'Archivo Black',

}
  return (
    <html lang="en">
      <head>
        <title>Somafy</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </head>
      <body style={style}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
